import { Inter } from 'next/font/google'
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Raports - Ramis\'s portfolios',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
